{
    "branch": "main",
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# FastAPI-YOLOv5 Changelog"
            }
        ],
        [
          "@semantic-release/exec",
          {
            "prepareCmd": "printf '#!/usr/bin/env python\\n__version__ = \"%s\"\\n' ${nextRelease.version} > src/app/__init__.py"
          }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md",
                    "src/app/__init__.py"
                ],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
            }
        ],
    ]
}
