Environment: Production
Author: DCline
Region: us-west-2
MinCapacity: 1
MaxCapacity: 20
Account: 975513124282
ProjectName: FastAPI-YOLOv5
ProjectNumber: 901103-yv5
Description: This stack deploys a Fargate managed ELB environment for creating localized detections from a YOLOv5 model using the FastAPI framework with a general underwater megadetector
MODEL_WEIGHTS: s3://901103-models-deploy/midwatervars102/best.pt
MODEL_LABELS: s3://901103-models-deploy/midwatervars102/labels.txt
MODEL_DESCRIPTION: Megadetector
MODEL_INPUT_SIZE: 1280