FROM node:20-slim as app

LABEL vendor="MBARI"
LABEL maintainer="dcline@mbari.org"
LABEL license="Apache License 2.0"

ARG GIT_VERSION=latest
ARG IMAGE_URI=mbari/fastapi-yolov5-fargate-elb:${GIT_VERSION}

# Install the required node modules, and force the latest version of aws-cdk
RUN npm install -g aws-cdk@2.141.0

RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y curl && \
    apt-get install -y openssl && \
    apt-get install -y musl-dev && \
    apt-get install -y unzip && \
    apt-get install -y python3 python3-pip && \
    apt install -y python3.11-venv && \
    ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1 && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf \
        awscliv2.zip \
    && apt-get -y purge curl \
    && apt-get -y purge unzip \
    && rm -rf /var/lib/apt/lists/*

# Create a virtual environment and run install in that 
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"
RUN python3 -m pip install --upgrade pip>=23.3.0
RUN pip3 install aws-cdk-lib pyyaml

WORKDIR /tmp

RUN if [ "$GIT_VERSION" != "latest" ]; then \
    git clone -b v${GIT_VERSION} --depth 1 https://github.com/mbari-org/fastapi-yolov5.git ; \
    else \
    git clone --depth 1 https://github.com/mbari-org/fastapi-yolov5.git ; \
    fi

WORKDIR /app

RUN mv /tmp/fastapi-yolov5/* .

ARG DOCKER_GID=998
ARG DOCKER_UID=582

# Create a user with a specific UID and GID and add to docker group
RUN groupadd -g ${DOCKER_GID} docker && \
    useradd -u ${DOCKER_UID} -g ${DOCKER_GID} -m docker_user

RUN chown -R docker_user:docker /home/docker_user && \
    chown -R docker_user:docker /app

# Run as the docker user
USER docker_user

ENV PATH="$PATH:/app/node_modules/.bin"
ENTRYPOINT [ "/app/entrypoint.sh" ]

