services:
  app:
    build: src
    ports:
      - "8000:80"
    environment:
      - MODEL_DESCRIPTION=${MODEL_DESCRIPTION:-"Megadetector"}
      - MODEL_INPUT_SIZE=1280
# Example below to add for either local or cloud deployment
#      - MODEL_WEIGHTS=/app/models/midwater/best.pt # Local model deployment
#      - MODEL_LABELS=/app/models/midwater/labels.txt # Local model deployment
#      - MODEL_WEIGHTS=s3://901103-models-deploy/midwatervars102/best.pt # Cloud model deployment
#      - MODEL_LABELS==s3://901103-models-deploy/midwatervars102/labels.txt
# Model checkpoints in the above path must be called best.pt and labels for this model one per each line in labels.txt
#    volumes:
#      - ./src/app/model:/app/models/midwater # Local model deployment
#      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro # Testing cloud model deployment locally - not needed for CDK deployment
